name: Generate

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate-wikitext:
    name: Generate wikitext from spreadsheet data.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository.
        uses: actions/checkout@v3

      - name: Configure Python.
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install Python dependencies.
        run: pip install -r requirements.txt

      - name: Generate wikitext.
        run: python stream-index.py -d -u
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          MEDIAWIKI_BOT_USER: ${{ secrets.MEDIAWIKI_BOT_USER }}
          MEDIAWIKI_BOT_PASSWORD: ${{ secrets.MEDIAWIKI_BOT_PASSWORD }}
          UPDATE_REASON: ${{ github.event_name == 'push' && 'the script was updated' || 'of a scheduled update' }}

      - name: Upload generated wikitext.
        uses: actions/upload-artifact@v4
        with:
          name: stream-index
          path: stream-index.txt
          compression-level: 9
